export type Palestrante = {
    foto: string;
    nome: string;
    descricao: string;
    logo: string;
};

export const palestrantes: Palestrante[] = [
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/ALFREDO-1.png",
        nome: "Alfredo Soares",
        descricao: "Cofundador da Vtex e G4 Educação",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-g4-1.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/JOAO-KEPLER-1.png",
        nome: "João Kepler",
        descricao: "CEO da Smart Private Equity",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-bossa.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/NICOLAS-CHARAO-3.png",
        nome: "Nicolas Charão",
        descricao: "Criador do Método Agências de Elite",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-age.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/ANDRE-SIQUEIRA-2.png",
        nome: "André Siqueira",
        descricao: "Cofundador da RD Station",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-RDstation-1.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/AmandaMaria-1.png",
        nome: "Amanda Maria",
        descricao: "Criadora do Método VAP",
        logo: "/logos/amanda-maria.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/MarceloRoxo.png",
        nome: "Marcelo Roxo",
        descricao: "Neurociência do Consumo",
        logo: "/logos/marcel-roxo.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/JOAO-BROGNOLI-1.png",
        nome: "João Brognoli",
        descricao: "Fundador Duo And Co",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-duo.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/RafelKiso-2.png",
        nome: "Rafael Kiso",
        descricao: "CMO da Mlabs",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-mlab.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/CAMILA-1.png",
        nome: "Camila Renaux",
        descricao: "Marketing Estratégico",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-camila.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/CAROL-LIMA-3.png",
        nome: "Carol Lima",
        descricao: "Estratégia de Conteúdo",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-hubfy.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/LUCAS-PIMENTA-2.png",
        nome: "Lucas Pimenta",
        descricao: "Marketing Político",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-lucas-pimenta.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/CRISTIANO-SANTOS-2.png",
        nome: "Cristiano Santos",
        descricao: "Mídias Sociais e Personal Branding",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-likedin-top-voice.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/RAFAEL-LIPORACE-1.png",
        nome: "Rafael Liporace",
        descricao: "CEO e Cofundador da Tardezinha",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-tardezinha.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/Hanah-Franklin.png",
        nome: "Hanah Franklin",
        descricao: "Storytelling e Conteúdo Estratégico",
        logo: "/logos/hanah-franklin.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/Ben.png",
        nome: "Ben Ludmer",
        descricao: "Criador do Método Abracadabra",
        logo: "/logos/ben-ludmer.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/DjalmaPinheiro.png",
        nome: "Djalma Pinheiro",
        descricao: "Mentor dos Pequenos Gigantes",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-sushi.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/ALCIDES-NETTO-1.png",
        nome: "Alcides Netto",
        descricao: "Produção Publicitária e Audiovisual",
        logo: "/logos/alcides-netto.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/2REC-1.png",
        nome: "Dois Rec",
        descricao: "Marketing e posicionamento de Marca",
        logo: "/logos/dois-rec.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/CARLOS-OSHIRO_-1.png",
        nome: "Carlos Oshiro",
        descricao: "Fundador da Targo Consultoria",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-targo.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/RODRIGO-1.png",
        nome: "Rodrigo Araújo",
        descricao: "Marketing, vendas e Branding",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-digital-comunicacao.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/FERNANDO-MIRANDA-2.png",
        nome: "Fernando Miranda",
        descricao: "CEO da Staage",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-staage-1.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/FABRICIO-ALVA.png",
        nome: "Fabricio Alva",
        descricao: "Estratégia e Performance Empresarial",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-fabrica-alva.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/AIMEEGOMES.png",
        nome: "Aimee Gomes",
        descricao: "Tráfego Pago e Marketing Digital",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-bemol.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/Glauber.png",
        nome: "Glauber Gomes",
        descricao: "Estratégia, IA e Produtos Digitais",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-rumo-mkt.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/LUIZ-EDUARDO-1.png",
        nome: "Luiz Eduardo",
        descricao: "Líder em Estratégias Digitais",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-rumo-mkt-2.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/Breno-Maciel.png",
        nome: "Breno Maciel",
        descricao: "CEO da Vanguarda Martech",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-vanguarda.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/Rodrigo-Kallas.png",
        nome: "Rodrigo Kallas",
        descricao: "CEO da Kallas Mídia OOH",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-kallas.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/RODRIGOWUAGHAN-1.png",
        nome: "Rodrigo Waughan",
        descricao: "Presidente do grupo Gérbera",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-gerbera.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/RAFAEL-AMORIN-3.png",
        nome: "Rafael Amorim",
        descricao: "Liderança comercial e expansão de negócios",
        logo: "/logos/rafael-amorim.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/GersonToller.png",
        nome: "Gerson Toller",
        descricao: "Especialista em IA aplicada ao Varejo",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-soulPlus.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/Marc-Tawl.png",
        nome: "Marc Tawil",
        descricao: "Instrutor oficial do Linkedin learning",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-linkedin-learning.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/06/RobertaGaspar-1.png",
        nome: "Roberta Gaspar",
        descricao: "Coo do all in club",
        logo: "https://dsx.com.vc/wp-content/uploads/2025/06/logo-all-in-club.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/Mauricio-Stellato.png",
        nome: "Maurício Stellato",
        descricao: "Referência nacional em automação de conversas e estratégia com IA.",
        logo: "/logos/mauricio-stellato.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/BiancaGuedes.png",
        nome: "Bianca Guedes",
        descricao: "Triatleta e influenciadora digital, referência em performance e autenticidade.",
        logo: "/logos/bianca-guedes.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/MariahCris.png",
        nome: "Mariah Acris",
        descricao: "Diretora audiovisual e publicitária.",
        logo: "/logos/mariah-acris.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/Jack-Serafim-1.png",
        nome: "Jack Serafim",
        descricao: "Especialista em marketing político, comunicação pública e posicionamento estratégico.",
        logo: "/logos/jack-serafim.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/CarolGuerra.png",
        nome: "Carol Guerra",
        descricao: "Especialista em branding, posicionamento e marcas de luxo no Norte do Brasil.",
        logo: "/logos/carol-guerra.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/SuelenScop.png",
        nome: "Suelen Scop",
        descricao: "COO da Singulari Consultoria",
        logo: "/logos/suelen-scop.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/GiseleOshiro.png",
        nome: "Gisele Oshiro",
        descricao: "CEO da Targo Consultoria",
        logo: "/logos/gisele-oshiro.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/AlexMota.png",
        nome: "Alex Mota",
        descricao: "Head de Marketing da Construtora Engeco e especialista em marketing de luxo",
        logo: "/logos/alex-mota.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/ErickFernandes.png",
        nome: "Erick Fernandes",
        descricao: "Diretor Comercial do Centro do Alumínio",
        logo: "/logos/erick-fernandes.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/JaquelineGuedes.png",
        nome: "Jacqueline Guedes",
        descricao: "CEO da Empower Palestras",
        logo: "/logos/jacqueline-guedes.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/JessicaNery.png",
        nome: "Jéssica Nery",
        descricao: "Especialista em Marketing Digital e Vendas",
        logo: "/logos/jessica-nery.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/MagnoRodrigues.png",
        nome: "Magno Rodrigues",
        descricao: "Fundador do Pega Bizu",
        logo: "/logos/magno-rodrigues.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/MarcosEvangelista.png",
        nome: "Marcus Evangelista",
        descricao: "Especialista em Crescimento no Instagram",
        logo: "/logos/marcus-evangelista.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/Diego-Cestaro.png",
        nome: "Diego Cestaro",
        descricao: "CEO da AmazonCopy e AC Display",
        logo: "/logos/diego-cestaro.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/Flavia-Sausmikat.png",
        nome: "Flávia Sausmikat",
        descricao: "Referência em pesquisa qualitativa e comportamento do consumidor.",
        logo: "/logos/flavia-sausmikat-soares.png",
    },
    {
        foto: "https://dsx.com.vc/wp-content/uploads/2025/07/Afranio-Soares-Filho.png",
        nome: "Afrânio Soares Filho",
        descricao: "Referência regional em inteligência de mercado, análise estratégica e pesquisa eleitoral.",
        logo: "/logos/afranio-soares-filho.png",
    }
];